from django.urls import path
from .views import *
from rest_framework_simplejwt import views as jwt_views


urlpatterns = [
    path('search/', search_box),
    path('change-responsible-issue/', change_responsible_issue),
    path('create-coment-for-issue/', create_coment_for_issue),
    path('create-coment-for-task/', create_coment_for_task),
    path('create-coment-for-userstory/', create_coment_for_userstory),
    path('create-task-for-userstory/', create_task_for_userstory),
    path('create-userstory-for-sprint/', create_userstory_for_sprint),
    path('create-coment-for-sprint/', create_coment_for_sprint),
    path('form-add-issue/<int:id>', form_add_issue),
    path('form-add-sprint/<int:id>', form_add_sprint),
    path('create-issue/', create_issue),
    path('create-sprint/', create_sprint),
    path('create-project/', create_project),
    path('coment-for-task/<int:id>', coment_for_task),
    path('change-status-userstory/', change_status_userstory),
    path('userstory/<int:id>', user_story),
    path('change-responsible-userstory/', change_responsible_userstory),
    path('task/<int:id>', task),
    path('change-responsible-task/', change_responsible_task),
    path('user/<int:id>', user_info),
    path('sprint/<int:id>', sprint),
    path('change-status-task/', change_status_task),
    path('change-status-sprint/', change_status_sprint),
    path('change-responsible-sprint/', change_responsible_sprint),
    path('change-status-issue/', change_status_issue),
    path('change-status-issue-two/', change_status_issue_two),
    path('list-issues-two/<int:id>', list_issues_two),
    path('list-issues/<int:id>', list_issues),
    path('issue-info/<int:id>', issue_info),
    path('members-project/<int:id>', members_project),
    path('my-project/<int:id>', my_project),
    path('entrance', entrance),
    path('homepage', home_page),
    path('login', enter),
    path('logout', log_out),
    path('register', register),
    path('invite', invite),
    path('sendinvitation', send_invitation),
    path('emailconfirmation', emailconfirmation),
]