# Generated by Django 2.2.6 on 2021-04-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'В ОБРАБОТЕ'), ('PAID', 'ОПЛАЧЕН'), ('NO', 'ОТКЛОНЬОН'), ('READY', 'ГОТОВ К ВЫДАЧЕ')], max_length=5, null=True),
        ),
    ]
