# Generated by Django 2.2.6 on 2021-06-04 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='courseparticipant',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_participant', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='courseparticipant',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_participant', to='courses.Student'),
        ),
    ]
